language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

services:
  - postgresql

install:
  - python setup.py develop

before_script:
    - "TMPDIR=`mktemp -d`"
    - psql -c 'create database hgt_test;' -U postgres
    - psql -U postgres -d hgt_test -c "create extension postgis;"

script:
  - python setup.py test
  - flake8
  - "gmalt-hgtread 1.0001 10.0001 gmaltcli/test/srtm3/N00E010.hgt | grep \"Value: 57\""
  - "gmalt-hgtread 1.0001 10.0001 gmaltcli/test/srtm3/N00E010.hgt | grep \"Location: (0P,0L)\""
  - "gmalt-hgtread 0.861295 10.339703 gmaltcli/test/srtm3/N00E010.hgt | grep \"Value: 644\""
  - "gmalt-hgtread 0.861295 10.339703 gmaltcli/test/srtm3/N00E010.hgt | grep \"Location: (408P,166L)\""
  - "gmalt-hgtread 1.0001 10.0001 gmaltcli/test/srtm1/N00E010.hgt | grep \"Value: 57\""
  - "gmalt-hgtread 1.0001 10.0001 gmaltcli/test/srtm1/N00E010.hgt | grep \"Location: (0P,0L)\""
  - "gmalt-hgtread 0.861295 10.339703 gmaltcli/test/srtm1/N00E010.hgt | grep \"Value: 646\""
  - "gmalt-hgtread 0.861295 10.339703 gmaltcli/test/srtm1/N00E010.hgt | grep \"Location: (1223P,499L)\""
  - "gmalt-hgtget small $TMPDIR"
  - "ls $TMPDIR | wc -l | grep 6"
  - "ls $TMPDIR | grep '^N00E009.hgt.zip$'"
  - "ls $TMPDIR | grep '^N00E009.hgt$'"
  - "md5sum -b $TMPDIR/N00E009.hgt | grep '0dc319cb922bac1b7ccefa0b55688a51'"
  - "gmalt-hgtload -vv -tb -c 2  -u postgres -d hgt_test -H '' -t elevation gmaltcli/test/import/"
  - psql -U postgres -d hgt_test -c "SELECT COUNT(*) FROM elevation;"
