language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - python setup.py develop

before_script:
    - "TMPDIR=`mktemp -d`"

script:
  - python setup.py test
  - "gmalt-hgtread 1.0001 10.0001 gmaltcli/test/N00E010.hgt | grep \"Value: 57\""
  - "gmalt-hgtread 1.0001 10.0001 gmaltcli/test/N00E010.hgt | grep \"Location: (0P,0L)\""
  - "gmalt-hgtread 0.861295 10.339703 gmaltcli/test/N00E010.hgt | grep \"Value: 644\""
  - "gmalt-hgtread 0.861295 10.339703 gmaltcli/test/N00E010.hgt | grep \"Location: (408P,166L)\""
  - "gmalt-hgtget small $TMPDIR"
  - "[ `ls $TMPDIR | wc -l` -eq "6" ]"
